version: '3.1'

services:
  product-x:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: product
    container_name: product-app
    restart: always
    networks:
      - store-network
    ports:
      - "8080:8080"

  db:
    image: mysql
    container_name: products-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - store-network
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: store

  adminer:
    image: adminer
    restart: always
    networks:
      - store-network
    ports:
      - "8081:8080"

networks:
  store-network:
    driver: bridge
